export const CLEAR_ERROR = "CLEAR_ERROR"

// fetching all items
export const ALL_ITEMS_REQUEST = "ALL_ITEMS_REQUEST"
export const ALL_ITEMS_SUCCESS = "ALL_ITEMS_SUCCESS"
export const ALL_ITEMS_FAILS = "ALL_ITEMS_FAILS"


// fetching an items
export const AN_ITEM_REQUEST = "AN_ITEM_REQUEST"
export const AN_ITEM_SUCCESS = "AN_ITEM_SUCCESS"
export const AN_ITEM_FAILS = "AN_ITEM_FAILS"


// fetching an items
export const AN_RESTAURANT_REQUEST = "AN_RESTAURANT_REQUEST"
export const AN_RESTAURANT_SUCCESS = "AN_RESTAURANT_SUCCESS"
export const AN_RESTAURANT_FAILS = "AN_RESTAURANT_FAILS"


// fetching all RESTAURANTS
export const ALL_RESTAURANT_REQUEST = "ALL_RESTAURANT_REQUEST"
export const ALL_RESTAURANT_SUCCESS = "ALL_RESTAURANT_SUCCESS"
export const ALL_RESTAURANT_FAILS = "ALL_RESTAURANT_FAILS"

// user login constants
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILS = "LOGIN_FAILS"

// user register constants
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILS = "REGISTER_USER_FAILS"


// load user if jwt token exist
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAILS = "LOAD_USER_FAILS"

// logout user
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAILS = "LOGOUT_USER_FAILS"

// user UPDATE constants
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAILS = "UPDATE_PASSWORD_FAILS"

// add resturant
export const REGISTER_RESTAURANT_REQUEST = "REGISTER_RESTAURANT_REQUEST"
export const REGISTER_RESTAURANT_SUCCESS = "REGISTER_RESTAURANT_SUCCESS"
export const REGISTER_RESTAURANT_FAILS = "REGISTER_RESTAURANT_FAILS"

// add item 
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILS = "ADD_ITEM_FAILS"

// get all reviews item or restaurant
export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST"
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS"
export const ALL_REVIEWS_FAILS = "ALL_REVIEWS_FAILS"

//get loggedin user review item/restaurant
export const USER_REVIEW_REQUEST = "USER_REVIEW_REQUEST"
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS"
export const USER_REVIEW_FAILS = "USER_REVIEW_FAILS"

// add review 
export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST"
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAILS = "ADD_REVIEW_FAILS"

// delete review
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAILS = "DELETE_REVIEW_FAILS"